giftchanger/urls.py
from django.urls import path
from . import views

from django.views.generic import TemplateView, RedirectView


app_name = "giftchanger"
urlpatterns = [
    path("", TemplateView.as_view(template_name="giftchanger/main.html"), name="top"),

    path("event_register", views.admin_register_view, name="event_register_view"),
    path("event_register_post/", views.admin_register_post, name="event_register_post"),
    path("register_completed/<uuid:pk>", views.RegisterCompletedView.as_view(), name="register_completed"),

    path("user_login/", TemplateView.as_view(template_name="giftchanger/user_login.html"), name="user_login"),
    path("user_login_post/", views.user_login_post, name="user_login_post"),
    path("<uuid:pk>/edit/", views.AdminEditView.as_view(), name="admin_edit"),
    path("<uuid:pk>/event_edit_post/", views.admin_edit_post, name="event_edit_post"),

    path("<uuid:pk>/match_with_ttc/", views.ttc_result_post, name="matching_result_post"),
    path("<uuid:pk>/event_result/", views.EventResultView.as_view(), name="event_result"),

    path("<uuid:pk>/user_login/", views.user_login_confirm, name="user_login_confirm"),
    path("user_login/<uuid:pk>/", RedirectView.as_view(permanent=True, pattern_name="giftchanger:user_login_confirm")),
    path("<uuid:pk>/", RedirectView.as_view(permanent=True, pattern_name="giftchanger:user_login_confirm")),

    path("<uuid:event_id>/create_user_post/", views.create_user_post, name="create_user_post"),
    path("<uuid:event_id>/<int:pk>/edit_gift/", views.GiftEditView.as_view(), name="edit_gift"),
    path("<uuid:event_id>/<int:pk>/edit_gift_post/", views.edit_gift_post, name="edit_gift_post"),

    path("<uuid:event_id>/<int:pk>/preferences_check/", views.preference_edit_check, name="edit_preferences_check"),
    path("<uuid:event_id>/<int:pk>/edit_preferences/", views.preference_edit, name="edit_preferences"),
    path("<uuid:event_id>/<int:pk>/post_preferences/", views.preference_post, name="post_preferences"),
    path("<uuid:event_id>/<int:pk>/preference_saved/", views.PreferenceSavedView.as_view(), name="preference_saved"),

    path("view_event/<str:event_id>/", views.view_event, name="view_event"),


]

ttcgiftchanger/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("giftchanger.urls"))
]

giftchanger/models.py
from django.db import models
import datetime
# Create your models here.


class Event(models.Model):
    creation_date = models.DateTimeField("date created")
    event_date = models.DateField(default=datetime.date.today)
    email = models.EmailField()
    number_of_gifts = models.IntegerField(default=8)
    show_name_before_match = models.BooleanField(default=False)
    show_name_after_match = models.BooleanField(default=True)
    password = models.CharField(max_length=30)
    event_name = models.CharField(max_length=50)
    event_id = models.CharField(max_length=36, primary_key=True)
    allow_picture = models.BooleanField(default=False)
    force_picture = models.BooleanField(default=False)
    result = models.CharField(max_length=20000, default="")


class Gift(models.Model):
    parent_event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user_name = models.CharField(max_length=20)
    gift_title = models.CharField(max_length=40, default="")
    gift_description = models.CharField(max_length=1000, default="")
    preference_list_str = models.CharField(max_length=10000, default="")
    not_selected_list_str = models.CharField(max_length=10000, default="")
    image_url = models.CharField(max_length=100, null=True)

giftchanger/forms.py
from django import forms
import PIL
from .models import Gift
import requests
import json
import random


class ImageFormRequired(forms.Form):
    image = forms.ImageField(label="ファイル選択...",
                             widget=forms.FileInput(
                                 attrs={'class': 'custom-file-input',
                                        "lang": "ja"}))


class ImageFormElective(forms.Form):
    image = forms.ImageField(required=False,
                             label="ファイル選択...",
                             widget=forms.FileInput(
                                 attrs={'class': 'custom-file-input',
                                        "lang": "ja"}))


class NoImageForm(forms.Form):
    pass


def imgur_uploader(image_file, name="image", content_type=None):
    endpoint = "https://api.imgur.com/3/image"
    client_ids = "2bf2542859d3f52", "3546e87c0ba5843", "7d12b6e8542631c"
    client_id = "Client-ID " + random.choice(client_ids)

    files = {'image': (name, image_file, content_type)}
    headers = {"Authorization": client_id}

    res = requests.post(endpoint, headers=headers, files=files)
    res_dict = json.loads(res.text)

    if res_dict["success"]:
        link = res_dict["data"]["link"]
        return link

    else:
        return res_dict

giftchanger/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.mail import send_mail, EmailMessage
# Create your views here.
from .models import Event, Gift
from django.utils import timezone
import uuid
from .ttc_cycle import ttc_algorithm
import os
import json
from django.urls import reverse, resolve
from django.views import generic

from .forms import ImageFormRequired, ImageFormElective, NoImageForm, imgur_uploader
from django import forms
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError


def admin_register_view(request):
    return render(request, "giftchanger/admin_register.html")


def admin_register_post(request):
    event = Event.objects.create(
        creation_date=timezone.now(),
        show_name_before_match=True if request.POST["show_name_before"] == "true" else False,
        show_name_after_match=True if request.POST["show_name_after"] == "true" else False,
        email=request.POST["email"],
        password=request.POST["password"],
        event_name=request.POST["event_name"],
        event_date=request.POST["event_date"],
        number_of_gifts=request.POST["number_of_gifts"],
        event_id=str(uuid.uuid4()),
        allow_picture=False if request.POST["allow_picture"] == "false" else True,
        force_picture=True if request.POST["allow_picture"] == "always" else False
    )

    # subject = "TTCプレゼント交換 イベント登録完了"
    # message = "参加者ログイン用URLとか送る。"
    # from_email = "piyopiyo@example.com"
    # to = [request.POST["email"]]
    # bcc = ["piyopiyopiyo@example.com"]

    # if os.getenv('GAE_INSTANCE'):
    #     from google.appengine.api import mail
    #     mail.send_mail(sender="noreply@piyo-220609.appspot.com",
    #                    to=to,
    #                    subject=subject,
    #                    body=message,)
    #
    # else:
    #
    #     email = EmailMessage(subject, message, from_email, to, bcc)
    #     email.send()

    # for Google App Engine
    return HttpResponseRedirect(reverse("giftchanger:register_completed", args=(event.event_id,)))


def admin_edit_post(request, pk):
    event = Event.objects.get(event_id=pk)

    event.show_name_before_match = True if request.POST["show_name_before"] == "true" else False
    event.show_name_after_match = True if request.POST["show_name_after"] == "true" else False
    event.email = request.POST["email"]
    event.password = request.POST["password"]
    event.event_name = request.POST["event_name"]
    event.event_date = request.POST["event_date"]
    event.number_of_gifts = request.POST["number_of_gifts"]

    event.allow_picture = False if request.POST["allow_picture"] == "false" else True
    event.force_picture = True if request.POST["allow_picture"] == "always" else False

    event.save()
    print(event.event_id)
    return HttpResponseRedirect(reverse("giftchanger:register_completed", args=(event.event_id,)))


class AdminEditView(generic.DetailView):
    model = Event
    template_name = "giftchanger/admin_edit.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        gifts = Gift.objects.filter(parent_event=context["event"])

        gift_registered_num = len(gifts)
        gift_finished_num = len(gifts.exclude(gift_title__exact=""))

        if gift_registered_num == context["event"].number_of_gifts:
            available_bool = True
            for gift in gifts:
                available_bool = available_bool and gift.preference_list_str
            context['match_available'] = available_bool
        else:
            context["match_available"] = False

        context["gift_registered_num"] = gift_registered_num
        context["gift_finished_num"] = gift_finished_num


        return context


class RegisterCompletedView(generic.DetailView):
    model = Event
    template_name = "giftchanger/admin_register_completed.html"


def user_login_post(request):
    event = Event.objects.get(
        event_date=request.POST.get("event_date"),
        event_name=request.POST.get("event_name")
    )
    return HttpResponseRedirect(reverse("giftchanger:user_login_confirm", args=(event.event_id,)))


# class UserLoginConfirmView(generic.DetailView):
#     model = Event
#     template_name = "giftchanger/user_login_confirm.html"

def ttc_result_post(request, pk):
    event = Event.objects.get(event_id=str(pk))
    gifts_queryset = Gift.objects.filter(parent_event=event)
    if len(gifts_queryset) == event.number_of_gifts:
        preferences = {}
        for gift in gifts_queryset:
            if len(json.loads(gift.preference_list_str)) == event.number_of_gifts:
                preferences[gift.id] = json.loads(gift.preference_list_str)
        if len(preferences) == event.number_of_gifts:

            # print(preferences)
            # result_str = ""
            result_list = ttc_algorithm(preferences)

            for list1 in result_list:
                for list2 in list1:
                    for i in range(len(list2)):
                        list2[i] = gifts_queryset.get(id=list2[i]).user_name

            for list1 in result_list:
                for i in range(len(list1)):
                    list1[i] = json.dumps(list1[i], ensure_ascii=False, separators=('→', ':'))

            result_str = json.dumps(result_list, ensure_ascii=False).replace("\\", "").replace('"', "")

            event.result = result_str
            event.save()

            return HttpResponseRedirect(reverse("giftchanger:event_result", args=(event.event_id, )))


class EventResultView(generic.DetailView):
    model = Event
    template_name = "giftchanger/event_result.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        result_str = context["event"].result
        context["result"] = result_str

        gifts = Gift.objects.filter(parent_event=context["event"])

        gift_registered_num = len(gifts)
        gift_finished_num = len(gifts.exclude(gift_title__exact=""))

        if gift_registered_num == context["event"].number_of_gifts:
            available_bool = True
            for gift in gifts:
                available_bool = available_bool and gift.preference_list_str
            context['match_available'] = available_bool
        else:
            context["match_available"] = False

        context["gift_registered_num"] = gift_registered_num
        context["gift_finished_num"] = gift_finished_num

        return context


def user_login_confirm(request, pk):
    event = Event.objects.get(
        event_id=pk
    )
    num_gifts = len(Gift.objects.filter(parent_event=event))
    print(num_gifts)
    if num_gifts < event.number_of_gifts:
        return render(request, "giftchanger/user_login_confirm.html", context={"event": event, "current_num_gifts": str(num_gifts)})

    else:
        return render(request, "giftchanger/user_login_failure.html", context={"event": event, "current_num_gifts": str(num_gifts)})


def create_user_post(request, event_id):
    event = Event.objects.get(event_id=event_id)
    num_gifts = len(Gift.objects.filter(parent_event=event))
    if num_gifts < event.number_of_gifts:
        gift = Gift.objects.get_or_create(
            parent_event=event,
            user_name=request.POST["user_name"],
        )[0]
        return HttpResponseRedirect(reverse("giftchanger:edit_gift", args=(event_id, gift.id)))
    else:
        gift = get_object_or_404(Gift, parent_event=event, user_name=request.POST["user_name"])
        return HttpResponseRedirect(reverse("giftchanger:edit_gift", args=(event_id, gift.id)))


def edit_gift_post(request, event_id, pk):
    event = Event.objects.get(
        event_id=event_id
    )
    gift = Gift.objects.get(
        parent_event=event,
        id=pk,
    )
    gift.gift_title = request.POST["gift_title"]
    gift.gift_description = request.POST["gift_description"]

    form = ImageFormRequired(request.POST, request.FILES)

    if form.is_valid():
        upload_result = imgur_uploader(request.FILES["image"].read(), request.FILES["image"].name, request.FILES["image"].content_type)

        if isinstance(upload_result, str):
            gift.image_url = upload_result
        else:
            pass

    gift.save()
    return HttpResponseRedirect(reverse("giftchanger:edit_preferences_check", args=(event_id, gift.id)))


class GiftEditView(generic.DetailView):
    model = Gift
    template_name = "giftchanger/gift_edit.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if context["gift"].parent_event.allow_picture:
            if context["gift"].parent_event.force_picture:
                context["image_form"] = ImageFormRequired()
            else:
                context["image_form"] = ImageFormElective()
        else:
            context["image_form"] = NoImageForm()
        return context


def preference_edit_check(request, event_id, pk):
    event = Event.objects.get(event_id=event_id)
    gifts = Gift.objects.filter(parent_event=event)
    gift_registered_num = len(gifts)
    gift_finished_num = len(gifts.exclude(gift_title__exact=""))
    if event.number_of_gifts == gift_registered_num:
        return HttpResponseRedirect(reverse("giftchanger:edit_preferences", args=(event_id, pk)))
    else:
        return render(request, "giftchanger/preference_check.html", context={"event": event, "gift_registered_num": gift_registered_num, "gift_finished_num": gift_finished_num})


def preference_edit(request, event_id, pk):
    parent_event = Event.objects.get(event_id=event_id)
    gifts_list = Gift.objects.filter(parent_event=parent_event)

    # create json to send and store in the LocalStorage.
    gifts_json = json.dumps([{'key': gift.id,
                              'value': {"title": gift.gift_title, "name": gift.user_name,

giftchanger/templates/giftchanger/_base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>{% block title %}TTC交換マッチング用サイト{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Custom styles for this template -->
  <!--
    <link href="starter-template.css" rel="stylesheet">
    -->
  </head>

  <body>

    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="">最適交換マッチング</a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse" id="navbarsExample01" style="">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'giftchanger:top' %}">Home</a>
          </li>
            <li class="nav-item active">
            <a class="nav-link" href="{% url 'giftchanger:event_register_view' %}">交換を主催する</a>
          </li>
            <li class="nav-item active">
            <a class="nav-link" href="{% url 'giftchanger:user_login' %}">交換に参加する</a>
          </li>

{#          <li class="nav-item dropdown">#}
{#            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">イベントを主催</a>#}
{#            <div class="dropdown-menu" aria-labelledby="dropdown01">#}
{#              <a class="dropdown-item" href="{% url 'giftchanger:event_register_view' %}">イベントを登録</a>#}
{#              <a class="dropdown-item" href="{% url 'giftchanger:user_login' %}">イベントに参加</a>#}
{#              <a class="dropdown-item" href="#">Something else here</a>#}
{#            </div>#}
{#          </li>#}

        </ul>
{#        <form class="form-inline my-2 my-md-0">#}
{#          <input class="form-control" placeholder="Search" aria-label="Search" type="text">#}
{#        </form>#}
      </div>
    </nav>

    <main role="main" class="container">

      {% block main %}{% endblock %}

    </main><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous" defer></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous" defer></script>
  </body>
</html>

giftchanger/templates/giftchanger/admin_edit.html
{% extends "giftchanger/_base.html" %}

{% block title %}イベントを編集{% endblock %}
{% block main %}
    <div class="my-3">
            全員が選好を入力し終わったらマッチング可能になります。<br>
                <div class="col-12">参加者予定数: {{ event.number_of_gifts }}人</div>
    <div class="col-12">参加登録済み: {{ gift_registered_num }}人</div>
    <div class="col-12">プレゼント登録済み: {{ gift_finished_num }}人</div>
        </div>
    <div class="my-3">
    {% if match_available %}
            <form action="{% url 'giftchanger:matching_result_post' event.event_id %}">
                  {% csrf_token %}
                <input title="event_id" name="event_id" type="text" value="{{ event.event_id }}" hidden>
            <button class="btn btn-primary">マッチングを実行</button>
        </form>
        {% else %}
            <button class="btn btn-secondary">マッチングを実行</button>
        <br>

        {% endif %}
    </div>


    <form action="{% url 'giftchanger:event_edit_post' event.event_id %}" method="post">
        {% csrf_token %}

        <div class="form-label-group">
            <label for="event_name">イベント名(参加者ログインの際に使います。)</label>
            <input id="event_name" name="event_name" class="form-control" placeholder="イベント名" required="" autofocus="" value="{{ event.event_name }}"
                   type="text">
        </div>

        <div class="form-label-group">
            <label for="event_date">イベント開催日(参加者ログインの際に使います。)</label>
            <input id="event_date" name="event_date" class="form-control" placeholder="イベント開催日" required="" type="date" value="{{ event.event_date|date:"Y-m-d" }}">
        </div>

        <div class="form-label-group">
            <label for="email">※準備中のためメールは送信されません。<br>メールアドレス(ログイン用URLを送信します。)</label>
            <input id="email" name="email" class="form-control" placeholder="メールアドレス" value="{{ event.email }}" type="email">
        </div>

        <div class="form-label-group">
            <label for="number_of_gifts">ギフトの数</label>
            <input id="number_of_gifts" name="number_of_gifts" class="form-control" placeholder="ギフトの数" required=""
                   value="{{ event.number_of_gifts }}" type="number">
        </div>

        <div class="form-label-group" hidden>
            <label for="password">管理者用パスワード（編集の際に使用します。）</label>
            <input id="password" name="password" class="form-control" placeholder="管理パスワード" type="text" value="{{ event.password }}">
        </div>

        <label for="event_name">名前の表示（順位選択時）</label>
        <label><input type="radio" name="show_name_before" id="show_name_before" value="true"{% if event.show_name_before_match %} checked{% endif %}>表示する</label>
        <label><input type="radio" name="show_name_before" id="show_name_before" value="false"{% if not event.show_name_before_match %} checked{% endif %}>表示しない</label>
        <br>

    <span hidden>
        <label for="event_name">名前の表示（マッチング後）</label>
        <label><input type="radio" name="show_name_after" id="show_name_after" value="true" checked>表示する</label>
        <label><input type="radio" name="show_name_after" id="show_name_after" value="false">表示しない</label>
        <br>
</span>
<span>
        <label for="event_name">写真投稿：</label>
        <label><input type="radio" name="allow_picture" id="allow_picture" value="true"{% if event.allow_picture and not event.force_picture %} checked{% endif %}>許可する</label>
        <label><input type="radio" name="allow_picture" id="allow_picture" value="false"{% if not event.allow_picture %} checked{% endif %}>許可しない</label>
        <label><input type="radio" name="allow_picture" id="allow_picture" value="always"{% if event.allow_picture and event.force_picture %} checked{% endif %}>強制</label>
        <br>
</span>
        <button class="btn btn-primary">送信してイベントを修正</button>
    </form>

{% endblock %}

giftchanger/templates/giftchanger/admin_register.html
{% extends "giftchanger/_base.html" %}

{% block title %}イベントを登録{% endblock %}
{% block main %}
    <form action="{% url 'giftchanger:event_register_post' %}" method="post">
        {% csrf_token %}

        <div class="form-label-group">
            <label for="event_name">イベント名(参加者ログインの際に使います。)</label>
            <input id="event_name" name="event_name" class="form-control" placeholder="イベント名" required="" autofocus="" type="text">
        </div>

        <div class="form-label-group">
            <label for="event_date">イベント開催日(参加者ログインの際に使います。)</label>
            <input id="event_date" name="event_date" class="form-control" placeholder="イベント開催日" required="" type="date">
        </div>

        <div class="form-label-group">
            <label for="email">※準備中のためメールは送信されません。<br>メールアドレス(ログイン用URLを送信します。)</label>
            <input id="email" name="email" class="form-control" placeholder="メールアドレス" value="test@example.com" type="email">
        </div>

        <div class="form-label-group">
            <label for="number_of_gifts">ギフトの数</label>
            <input id="number_of_gifts" name="number_of_gifts" class="form-control" placeholder="ギフトの数" required="" value="8" type="number">
        </div>

        <div class="form-label-group" hidden>
            <label for="password">管理者用パスワード（編集の際に使用します。）</label>
            <input id="password" name="password" class="form-control" placeholder="管理パスワード" type="text">
        </div>

        <label for="event_name">名前の表示（順位選択時）</label>
        <label><input type="radio" name="show_name_before" id="show_name_before" value="true">表示する</label>
        <label><input type="radio" name="show_name_before" id="show_name_before" value="false" checked>表示しない</label>
        <br>

    <span hidden>
        <label for="event_name">名前の表示（マッチング後）</label>
        <label><input type="radio" name="show_name_after" id="show_name_after" value="true" checked>表示する</label>
        <label><input type="radio" name="show_name_after" id="show_name_after" value="false">表示しない</label>
        <br>
</span>
        <label for="event_name">写真投稿：</label>
        <label><input type="radio" name="allow_picture" id="allow_picture" value="true">許可する</label>
        <label><input type="radio" name="allow_picture" id="allow_picture" value="false" checked>許可しない</label>
        <label><input type="radio" name="allow_picture" id="allow_picture" value="always">強制</label>
        <br>
        <button class="btn btn-primary">送信してイベントを作成</button>
    </form>

{% endblock %}

giftchanger/templates/giftchanger/admin_register_completed.html
{% extends "giftchanger/_base.html" %}

{% block title %}イベントを登録{% endblock %}
{% block main %}
    <h2 class="col-12">登録完了！</h2>
    <div class="col-12">以下のURLを保存し、参加者に参加者用URLを伝えてください。</div>
    <div class="col-12">イベント管理用URL: <a href="{{ request.scheme }}://{{ request.get_host }}{% url "giftchanger:admin_edit" event.event_id %}">{{ request.scheme }}://{{ request.get_host }}{% url "giftchanger:admin_edit" event.event_id %}</a></div>
    <div class="col-12">参加者用URL: <a href="{{ request.scheme }}://{{ request.get_host }}{% url "giftchanger:user_login_confirm" event.event_id %}">{{ request.scheme }}://{{ request.get_host }}{% url "giftchanger:user_login_confirm" event.event_id %}</a></div>
    <div class="col-12">参加定員: {{ event.number_of_gifts }}人</div>


{% endblock %}

giftchanger/templates/giftchanger/preference_check.html
{% extends "giftchanger/_base.html" %}
{% block title %}ほかの参加者を待機中{% endblock %}
{% block main %}
    <h2>選好入力画面 - 待機中</h2>
    <div>ほかの参加者が情報を入力するのを待っています。<br>
    今しばらくお待ちください。</div>
    <div class="col-12">参加者予定数: {{ event.number_of_gifts }}人</div>
    <div class="col-12">参加登録済み: {{ gift_registered_num }}人</div>
    <div class="col-12">プレゼント登録済み: {{ gift_finished_num }}人</div>
{% endblock %}

giftchanger/templates/giftchanger/user_login.html
{% extends "giftchanger/_base.html" %}

{% block title %}参加者ログイン{% endblock %}

{% block main %}

    <div class="mt-3 mx-aito">
        <form action="{% url 'giftchanger:user_login_post' %}" method="post">
            {% csrf_token %}
            <label for="event_name">イベント名</label>
            <input type="text" name="event_name" id="event_name">
            <br>
            <label for="event_date">イベント開催日</label>
            <input type="date" name="event_date" id="event_date">
            <br>
            <button class="btn btn-primary">
                ログイン
            </button>
        </form>
    </div>

{% endblock %}

giftchanger/templates/giftchanger/user_login_confirm.html
{% extends "giftchanger/_base.html" %}

{% block title %}イベントを登録{% endblock %}
{% block main %}
    <h2 class="col-12">このイベントに参加者としてログインします。</h2>
    <div class="col-12">イベント名: {{ event.event_name }}</div>
    <div class="col-12">参加者数: {{ event.number_of_gifts }}人</div>
    <br>
    <div class="col-12">名前の表示(選択時): {% if event.show_name_before_match == True %}あり{% else %}なし{% endif %}</div>
    <div class="col-12">名前の表示(マッチング後): {% if event.show_name_after_match == True %}あり{% else %}なし{% endif %}</div>
    <br>
    <form action="{% url 'giftchanger:create_user_post' event.event_id %}" method="post">
        {% csrf_token %}
        <div class="form-label-group">
            <label for="user_name">あなたの名前</label>
            <input id="user_name" name="user_name" class="form-control" placeholder="あなたの名前" required="" autofocus=""
                   type="text">
            <input id="event_id" name="event_id" value="{{ event.event_id }}" hidden>
            <button class="btn btn-primary">ログイン</button>
        </div>
    </form>


{% endblock %}

giftchanger/templates/giftchanger/user_login_failure.html
{% extends "giftchanger/_base.html" %}

{% block title %}イベントを登録{% endblock %}
{% block main %}
    <h2 class="col-12">このイベントに参加者としてログインします。</h2>
    <div class="col-12">イベント名: {{ event.event_name }}</div>
    <div class="col-12">参加者予定数: {{ event.number_of_gifts }}人</div>
    <div class="col-12">登録済み: {{ current_num_gifts }}人</div>
    <br>
    <br>
    登録済みの人数が、参加予定人数に達しました。<br>
    新規にイベントの参加登録を希望する方は。イベントの主催者に連絡してください。<br>
        <form action="{% url 'giftchanger:create_user_post' event.event_id %}" method="post">
        {% csrf_token %}
    <div class="form-label-group">
        <div class="mt-3">登録済みの方は、ここからログインできます。</div>
            <label for="user_name">あなたの名前</label>
            <input id="user_name" name="user_name" class="form-control" placeholder="あなたの名前" required="" autofocus=""
                   type="text">
            <input id="event_id" name="event_id" value="{{ event.event_id }}" hidden>
            <button class="btn btn-primary">ログイン</button>
        </div>
        </form>


{% endblock %}